### ISSUE TITLE
Panic when syncing many entities

### ISSUE THREAD

**Issue by mvesterli** [randomPoison/amethyst-editor-sync#12]
If the synchronization message is greater than supported by the socket, it fails to send and therefore panics.
On windows 10 this limit is 64kB, which is ~2500 empty entities and significantly less when components are involved.

This code causes the error on my machine.
```rust
extern crate amethyst;
extern crate amethyst_editor_sync;

use amethyst::prelude::*;
use amethyst_editor_sync::*;

struct TestState;

impl<'a, 'b> SimpleState<'a, 'b> for TestState {
    fn on_start(&mut self, data: StateData<GameData>) {
        for _ in 0..2_500 {
            data.world.create_entity().build();
        }
    }
}

fn main() -> amethyst::Result<()> {
    let editor_sync_bundle = SyncEditorBundle::new();
    let game_data = GameDataBuilder::default()
        .with_bundle(editor_sync_bundle)?;
    let mut game = Application::build(".", TestState)?
        .build(game_data)?;
    game.run();
    Ok(())
}
```

**Comment by randomPoison** [comment]
This would also be a good thing to add a regression test for!

**Comment by randomPoison** [comment]
Thinking about it a bit more, it's not going to be so trivial to convert to TCP 🤔 With TCP we'd have to manually manage connection states, send heartbeats, and track disconnections after a timeout. This is stuff we'll want to do eventually, but I'm not sure it's worth putting in that kind of effort for now. Instead I'm going to doing a pretty simple implementation of splitting the state message across multiple UDP packets.
