### ISSUE TITLE
Automatic registration of engine types

### ISSUE THREAD

**Issue by randomPoison** [randomPoison/amethyst-editor-sync#20]
The engine provides a lot of component and resource types and it quickly becomes a pain to manually remember every one that you need to register when using the editor with your game. It would be better if this crate provided a way to automatically register all the engine-provided types.

For convenience this functionality should be enabled by default, but there should be a way to disable it in case there is any use case where the user wouldn't want to register all the engine types.

Here's a list of types we should start with:

* `AmbientColor`
* `Light`
* `Named`
* `Shape`
* `RotationControl`
* `Camera`
* `Transform`
* `GlobalTransform`

**Comment by jojolepro** [comment]
Imo, I think it shouldn't be doing that by default.
Maybe a .with_default_types() function?

Also, amethyst will eventually have feature gates to reduce compilation times. Things like the renderer or the physics will be activable/deactivable by the end user. You should plan forward to that if possible.

**Comment by randomPoison** [comment]
This was closed by #21.
