### ISSUE TITLE
Setup bundle for easier, more configurable initialization

### ISSUE THREAD

**Issue by randomPoison** [randomPoison/amethyst-editor-sync#4]
#3 made setup for editor support easier by allowing users to register their component and resource types with `EditorSyncSystem` directly, removing the need manually register a separate system for each component/resource type. Unfortunately this change removed the ability to run serialization in parallel for each data type being serialized, so it would be good if we could take an alternate approach that allowed us to still register a separate system for each type while keeping the ergonomic improvements that #3 added.

Instead of registering the types directly with `EditorSyncSystem`, we should instead setup a bundle builder. Users would build the bundle similar to how they currently register their types with `EditorSyncSystem`, and then the bundle can register all the systems with `GameDataBuilder`. This approach would still be ergonomic for the user, but would allow us to regain the ability to serialize the game state in parallel.

## Notes

One ergonomic drawback is that users will also need to specify a system name for each type that they register. The signature for [`GameDataBuilder::with`](https://www.amethyst.rs/doc/master/doc/amethyst/struct.GameDataBuilder.html#method.with) requires a `&str` be used as the system name, which means we can't have the bundle generate a unique name for each system at runtime (which would be the preferred solution). As a first pass we can have users manually specify a name for each system, but later we should make a PR to amethyst to use a `Cow<'a, str>` for system names so that it can support runtime-generated `String` values for names.

**Comment by mvesterli** [comment]
Yeah, I thought of this approach after doing the other thing. I'll implement this.
I don't think users will have to supply a system name as that is only used when specifying dependencies as far as I'm aware. Since nothing will depend on these systems it shouldn't be an issue.
